#!/bin/sh /etc/rc.common
# basic setup at boot time

START=01
STOP=99

start() {
	mkdir -p /var/run
	mkdir -p /var/log
	mkdir -p /var/lock
	mkdir -p /var/state
	mkdir -p /var/tmp
	for CONF in /etc/sysctl.conf /etc/sysctl.d/*.conf; do
		[ -f "$CONF" ] && sysctl -p "$CONF" -e >&-
	done
}
