#!/bin/sh /etc/rc.common
#
# Start dropbear
#

START=55

start() {
	if [ ! -s /etc/dropbear/dropbear_rsa_host_key ]; then
		# Make sure rsa key is not empty or you won't
		# be able to connect via ssh
		rm /etc/dropbear/dropbear_rsa_host_key
	fi
	/usr/sbin/dropbear -R
}

stop() {
	killall dropbear
}
