#!/bin/sh
# Copyright (C) 2006 OpenWrt.org

run_scripts() {
	for i in /etc/rc.d/$1*; do
		if echo "$i" | grep -qs "module" ; then
			# Do not fork module loading
			[ -x $i ] && $i $2 2>&1
		else
			[ -x $i ] && $i $2 2>&1 &
		fi
	done | $LOGGER
}

LOGGER="cat"
[ -x /usr/bin/logger ] && LOGGER="logger -s -p 6 -t sysinit"

. $IPKG_INSTROOT/lib/functions.sh

run_scripts "$1" "$2"
source /etc/profile