#!/bin/sh
#
# Load Zipit Z2 Alsa settings
#

case "$1" in
  start)
	amixer sset "Headphones Playback ZC" on
	amixer sset "Speaker Playback ZC" on
	amixer sset "Right Speaker Playback Invert" on
	amixer sset "Playback 6dB Attenuate" on
	amixer sset "Right Mixer" on
	amixer sset "Left Mixer" on
	amixer sset "PCM" 237
	amixer sset "Headphone" 100
	amixer sset "Speaker" 115
	amixer sset "Treble" 14
	amixer sset "Bass" 13
	amixer sset "3D" 4
	;;
  stop)
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
