#!/bin/sh /etc/rc.common
#
# Setup Zipit Z2 LED's
#

START=11

start() {
	echo "Setting up Zipit LED's"
	echo "mmc0" > /sys/class/leds/z2\:green\:wifi/trigger
	echo "Z2-charging-blink-full-solid" > /sys/class/leds/z2\:green\:charged/trigger
	echo "none" > /sys/class/leds/z2\:amber\:charging/trigger
	STAT=`cat /sys/class/power_supply/Z2/status)`
	if [ "$STAT" == "Full" ]; then
		echo "255" > /sys/class/leds/z2\:green\:charged/brightness
	fi
}
