#!/bin/sh
# Suspend script

###### Pre-suspend ######
ifconfig wlan0 down 2>/dev/null
wpa_pid=`pidof wpa_supplicant`
wpa_stat=$?

if [ $wpa_stat -eq 0 ]; then
	kill -s SIGQUIT $wpa_pid
fi

#rmmod libertas_spi 2>/dev/null

# disable conservative cpufreq or zipit wont wake up
/etc/init.d/cpufreq stop

###### Suspend #######
echo "mem" > /sys/power/state

###### Resume ######
/etc/init.d/cpufreq start
#insmod /lib/modules/$(uname -r)/libertas_spi.ko 2>/dev/null

# If wpa_supplicant was running try to reconnect
if [ $wpa_stat -eq 0 ]; then
	/usr/sbin/wup &>/dev/null &
fi

