#!/bin/sh
# Suspend script

###### Pre-suspend ######
ifconfig wlan0 down 2>/dev/null
wpa_pid=`pidof wpa_supplicant`
wpa_stat=$?

if [ $wpa_stat -eq 0 ]; then
	kill -s SIGQUIT $wpa_pid
fi

# disable conservative cpufreq or zipit wont wake up
/etc/init.d/cpufreq stop

###### Suspend #######
echo "mem" > /sys/power/state

###### Resume ######
/etc/init.d/cpufreq start

# If wpa_supplicant was running try to reconnect (delayed)
if [ $wpa_stat -eq 0 ]; then
	(sleep 3 && /usr/sbin/wup &>/dev/null) &
fi